[package]
name = "adss-rs"
version = "0.1.0"
authors = ["eV <ev@7pr.xyz>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
strobe-rs = "0.6.2"
rand_core = "0.6.2"
rand = "0.8.3"

[dependencies.sharks]
default-features = false
version = "0.5.0"
path = "../sharks"
