on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

name: Tests

jobs:
  test:
    name: ${{matrix.rust}} on ${{matrix.os}}
    runs-on: ${{matrix.os}}

    strategy:
      matrix:
        rust: [1.54.0]
        os: [ubuntu-20.04]

    env:
      RUSTFLAGS: ''
      CARGO_PROFILE_DEV_DEBUG: '0' # reduce size of target directory

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
          token: ${{ secrets.CI_CHECKOUT_TOKEN }}

      - name: Toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          components: clippy, rustfmt
          toolchain: ${{matrix.rust}}
          override: true

      - name: Cache
        uses: Swatinem/rust-cache@v1

      - name: Format
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: -- --check ./src/lib.rs ./benches/bench.rs

      - name: Clippy
        uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --profile test --all-targets --all-features -- -D warnings

      - name: Test
        uses: actions-rs/cargo@v1
        with:
          command: test
